---
- name: Add key for Enpass
  apt_key:
    url: https://dl.sinew.in/keys/enpass-linux.key
- name: Add repository Enpass
  apt_repository:
    repo: deb http://repo.sinew.in/ stable main
    filename: ansible
- name: Install Enpass
  apt:
    name: enpass
    update_cache: yes
- name: Install base package
  apt: 
    name: "{{ item }}"
  with_items:
  - vim
  - git
  - powerline
  - tmux  
  - keyboard-configuration
  - console-setup
- name: Set keyboard US International
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^{{ item.name }}='
    line: '{{ item.name }}="{{ item.value }}"'
    create: yes
  with_items:
  - {name: 'XKBMODEL',   value: 'pc105'}
  - {name: 'XKBLAYOUT',  value: 'us'}
  - {name: 'XKBVARIANT', value: 'alt-intl'}
  - {name: 'XKBOPTIONS', value: 'compose:ralt'}
  notify:
  - restart keyboard
...
